version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend: # 환경변수 필요 없는 이유는 백엔드 이미지 배포 시 properties 파일을 secret 값으로 대체하여 작성되기 때문
    image: ${DOCKERHUB_USERNAME}/${PROJECT_BACKEND}:latest # Latest Backend Docker Image
    container_name: backend
    restart: always
    ports:
      - "8080:8080"

  frontend:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_FRONTEND}:latest # Latest Frontend Docker Image
    container_name: frontend
    restart: always
    ports:
      - "80:80"