version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${ MYSQL_PASSWORD } # 루트 비밀번호
      MYSQL_USER: ${ MYSQL_USER }             # 사용자
      MYSQL_PASSWORD: ${ MYSQL_PASSWORD }      # 사용자 비밀번호
      MYSQL_DATABASE: ${ MYSQL_DATABASE }      # DB Name
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  backend:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_BACKEND}:latest # Latest Backend Docker Image
    container_name: backend
    restart: always
    environment:
      MYSQL_HOST: ${ MYSQL_HOST }
      MYSQL_PORT: ${ MYSQL_PORT }
      MYSQL_USER: ${ MYSQL_USER }
      MYSQL_PASSWORD: ${ MYSQL_PASSWORD }
      MYSQL_DATABASE: ${ MYSQL_DATABASE }

      REDIS_HOST: ${ REDIS_HOST }
      REDIS_PORT: ${ REDIS_PORT }

      FRONTEND_ORIGIN: ${ FRONTEND_ORIGIN }

      JWT_SECRET_KEY: ${ JWT_SECRET_KEY }
      JWT_ACCESS_EXPIRATION: ${ JWT_ACCESS_EXPIRATION }
      JWT_REFRESH_EXPIRATION: ${ JWT_REFRESH_EXPIRATION }
    ports:
      - "8080:8080"

  frontend:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_FRONTEND}:latest # Latest Frontend Docker Image
    container_name: frontend
    restart: always
    ports:
      - "80:80"

volumes:
  mysql-data:
  redis-data: